#Text Box
txt_textboxUserName="id:userName"
txt_textboxUserEmail="id:userEmail"
txt_textboxCurrentAddress="id:currentAddress"
txt_textboxPermanentAddress="id:permanentAddress"
btn_textboxSubmit="id:submit"
output_textboxUserName="//p[@id='name']"
output_textboxEmail="//p[@id='email']"
output_textboxCurrentAddress="//p[@id='currentAddress']"
output_textboxPermanentAddress="//p[@id='permanentAddress']"
output_box="//div[@class='border col-md-12 col-sm-12']"

#Check box
unchecked_checkboxes="//*[@class='rct-icon rct-icon-uncheck']"
unchecked_branches="//*[@class='rct-collapse rct-collapse-btn']"
random_checkbox="//span[@class='rct-checkbox']/*[contains(@class, 'rct-icon rct-icon-')]"

#Radio button
radio_button_yes="//*[@for='yesRadio']"
radio_button_impressive="//*[@for='impressiveRadio']"
radio_button_no="//*[@for='noRadio']"
output_radio="//*[@class='mt-3']"

#Web Tables
first_nameofthelist_in_the_table="(//div[@class='rt-tr -odd']/div[@class='rt-td'])[1]"
third_nameofthelist_in_the_table="(//div[@class='rt-tr -odd']/div[@class='rt-td'])[8]"
text_search="id:searchBox"
btn_new_record="id:addNewRecordButton"
txt_firstname="id:firstName"
txt_lastname="id:lastName"
txt_userEmail="id:userEmail"
txt_userage="id:age"
txt_usersalary="id:salary"
txt_userdepartment="id:department"
btn_submitnewrecord="id:submit"
form_registration="//div[@class='modal-body']"
btn_close="//button[@class='close']"
btn_delete="//div[@class='rt-tr-group']/div/div[starts-with(.,'${id:firstName}')]/../div[@class='rt-td']/div/span[@title='Delete']"
btn_next="//div[@class='-next']/*[text() = 'Next']"
btn_previous="//div[@class='-previous']/*[text() = 'Previous']"
last_page="//span[@class='-totalPages']"
input_jump_to_page="//input[@aria-label='jump to page']"
rows_selector="//select[@aria-label='rows per page']"
addres_of_items="//div[@class='rt-tr-group']"

#Buttons
btn_double="id:doubleClickBtn"
btn_double_message="id:doubleClickMessage"
btn_context="id:rightClickBtn"
btn_context_message="id:rightClickMessage"
btn_one_click="xpath://*[text()='Click Me']"
btn_one_click_message="id:dynamicClickMessage"

#Links
simple_link="id:simpleLink"
dynamic_link="id:dynamicLink"
created_link="id:created"
no_content_link="id:no-content"
moved_link="id:moved"
bad_request_link="id:bad-request"
unauthorized_link="id:unauthorized"
forbidden_link="id:forbidden"
invalid_link="id:invalid-url"
response_link="id:linkResponse"

#Broken_links
img_valid="//div/img[@src='/images/Toolsqa.jpg']"
img_invalid="//div/img[@src='/images/Toolsqa_1.jpg']"
valid_link="//*[text()='Click Here for Valid Link']"
broken_link="//*[text()='Click Here for Broken Link']"

#Upload_Download
UploadFiletest="//*[@type='file']"
img_to_upload="D:/download.jpg"
filename="C:\\fakepath\\download.jpg"
path_upload="id:uploadedFilePath"
bownload_button="id:downloadButton"

#Dynamic_Properties
btn_enabled_in_5s="id:enableAfter"
btn_visiable_in_5s="id:visibleAfter"
btn_color_change_red="//button[@class='mt-4 text-danger btn btn-primary']"
btn_color_change_white="//button[@class='mt-4 btn btn-primary']"

#Practice_form
txt_practice_firstname="id:firstName"
txt_practice_lastname="id:lastName"
txt_practice_userEmail="id:userEmail"
radio_male="//label[text()='Male']"
radio_female="//label[text()='Female']"
radio_other="//label[text()='Other']"
txt_phone_number="id:userNumber"
date_picker="id:dateOfBirthInput"
date_picker_month="class:react-datepicker__month-select"
date_picker_year="class:react-datepicker__year-select"
txt_subject="id:subjectsInput"
checkbox_sports="//label[@for='hobbies-checkbox-1']"
checkbox_reading="//label[@for='hobbies-checkbox-2']"
checkbox_music="//label[@for='hobbies-checkbox-3']"
btn_UploadFile="//input[@id='uploadPicture']"
txt_address="id:currentAddress"
txt_state="id:react-select-3-input"
txt_city="id:react-select-4-input"
btn_delete_subject="//div[contains(@class, 'multi-value__remove')]/*"
output_subject="(//div[contains(@class, 'subjects-auto-complete__multi-value__label')])"
output_hobby_sports="//input[@id='hobbies-checkbox-1']"
output_hobby_reading="//input[@id='hobbies-checkbox-2']"
output_hobby_music="//input[@id='hobbies-checkbox-3']"
output_state="//div[contains(@class, '-singleValue')]"
output_city="//div[@id='city']//div[contains(@class, '-singleValue')]"

output_username="((//tbody/tr)[1]/td)[2]"
output_useremail="((//tbody/tr)[2]/td)[2]"
output_usergender="((//tbody/tr)[3]/td)[2]"
output_userphone="((//tbody/tr)[4]/td)[2]"
output_userdate_of_brth="((//tbody/tr)[5]/td)[2]"
output_user_subject="((//tbody/tr)[6]/td)[2]"
output_userhobby="((//tbody/tr)[7]/td)[2]"
output_userphoto="((//tbody/tr)[8]/td)[2]"
output_useraddress="((//tbody/tr)[9]/td)[2]"
output_user_state_city="((//tbody/tr)[10]/td)[2]"

summary_table="//div[@class='modal-content']"
